# test onepass, exa parsing (aka parsing towards ExaModels)
# todo:

parsing_backend!(:exa)

e_prefix!(:CTBase) # exceptions in code generated by @def are prefixed by CTBase (not by OptimalControl - the default) for tests

function test_onepass_exa()

    @testset "alias" begin

        o = @def begin
                v = (a, b) ∈ R², variable
                t ∈ [0, 1], time
                x ∈ R³, state
                u ∈ R⁴, control
                c = v₁ + b + x₁(0) + 2cos(x₃(1))
                c → min
        end
        @test o() isa ExaModels.ExaModel
        @test o(; grid_size = 100) isa ExaModels.ExaModel
        @test o(; backend = nothing) isa ExaModels.ExaModel
        @test o(; init = (1., 2., 3., 4., 5.)) isa ExaModels.ExaModel
        @test o(; base_type = Float32) isa ExaModels.ExaModel

        o = @def begin
                v = (a, b) ∈ R², variable
                t ∈ [0, 1], time
                x ∈ R, state
                u ∈ R⁴, control
                c = v₁ + b + x(0) + 2cos(x(1))
                c → min
        end
        @test o() isa ExaModels.ExaModel


    end

    @testset "time" begin

       o = @def begin
                v = (a, b) ∈ R², variable
                t ∈ [a, 1], time
                x ∈ R, state
                u ∈ R⁴, control
                c = v₁ + b + x(a) + 2cos(x(1))
                c → min
        end
        @test o() isa ExaModels.ExaModel

        o = @def begin
                v = (a, b) ∈ R², variable
                t ∈ [0, b], time
                x ∈ R, state
                u ∈ R⁴, control
                c = v₁ + b + x(0) + 2cos(x(b))
                c → min
        end
        @test o() isa ExaModels.ExaModel

        o = @def begin
                v = (a, b) ∈ R², variable
                t ∈ [a, b], time
                x ∈ R, state
                u ∈ R⁴, control
                c = v₁ + b + x(a) + 2cos(x(b))
                c → min
        end
        @test o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R, state
                u ∈ R⁴, control
                c = tf + x(0) + 2cos(x(tf))
                c → min
        end
        @test o() isa ExaModels.ExaModel

        t0 = 0
        o = @def begin
                t ∈ [t0, 1], time
                x ∈ R², state
                u ∈ R, control
                x₁(t0) + 2cos(x₂(1)) → min
        end

        tf = 1
        o = @def begin
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test o() isa ExaModels.ExaModel

    end

    @testset "constraint" begin

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                x₁(0) == 1
                x₂(tf) == 2
                -1 ≤ x₂(0) + x₁(tf) + tf ≤ 1
                tf ≤ 5
                tf^2 ≥ 5
                x₁(t) ≤ 1
                -1 ≤ u(t) ≤ 1
                cos(x₁(t)) ≤ 1
                cos(u(t)) ≤ 1
                x₁(t) + u(t) == 1
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                -1 ≤ x₂(0) + x₁(tf) + tf ≤ [1, 2]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test_throws CTBase.ParsingError o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                tf^2 ≥ [1, 5]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test_throws CTBase.ParsingError o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                cos(x₁(t)) ≤ [1, 2]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test_throws CTBase.ParsingError o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                cos(u(t)) ≤ [1, 2]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test_throws CTBase.ParsingError o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                x₁(t) + u(t) == [1, 2]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test_throws CTBase.ParsingError o() isa ExaModels.ExaModel

        o = @def begin
                tf ∈ R, variable
                t ∈ [0, tf], time
                x ∈ R², state
                u ∈ R, control
                x(0) == [1, 2]
                x₁(0) + 2cos(x₂(tf)) → min
        end
        @test o() isa ExaModels.ExaModel

   end

end